export const ErrorCodes = {
  AUTH_INVALID_INPUT: 'AUTH_INVALID_INPUT',
  AUTH_DUPLICATE_USERNAME: 'AUTH_DUPLICATE_USERNAME',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  ROOM_FULL: 'ROOM_FULL',
  ROOM_IN_GAME: 'ROOM_IN_GAME',
  ROOM_HOST_ONLY: 'ROOM_HOST_ONLY',
  ROOM_SPECTATOR_NOT_ALLOWED: 'ROOM_SPECTATOR_NOT_ALLOWED',
  GAME_NOT_ENOUGH_PLAYERS: 'GAME_NOT_ENOUGH_PLAYERS',
  GAME_ALREADY_STARTED: 'GAME_ALREADY_STARTED',
  SHOT_INPUT_SCHEMA_INVALID: 'SHOT_INPUT_SCHEMA_INVALID',
  CHAT_RATE_LIMITED: 'CHAT_RATE_LIMITED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
